Disable -Wunused-value for surfaceflinger
```
out/soong/.intermediates/frameworks/native/services/surfaceflinger/Tracing/tools/layertracegenerator/android_x86_64_silvermont/obj/frameworks/native/services/surfaceflinger/Scheduler/Scheduler.o frameworks/native/services/surfaceflinger/Scheduler/Scheduler.cpp
frameworks/native/services/surfaceflinger/Scheduler/Scheduler.cpp:432:29: error: ignoring temporary created by a constructor declared with 'nodiscard' attribute [-Werror,-Wunused-value]
  432 |                            (std::scoped_lock(mDisplayLock), displayId == mPacesetterDisplayId));
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Flag: EXEMPT b/369277774
Bug: b/369277774
Merged-In: Idd45525cc3fe15c3b5e66332650ce8b7811ae026
Change-Id: Idd45525cc3fe15c3b5e66332650ce8b7811ae026
(cherry picked from commit 91b33f18ea5416bfde82cda7fc1b210d9338a835)